#kubectl apply -f k8.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: custom-web-app
        image: edsonxp/gamie
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7777

---
apiVersion: v1
kind: Service
metadata:
  name: custom-web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 7777
    protocol: UDP
    targetPort: 7777
    nodePort: 30000
status:
  loadBalancer: {}